name: ghaflow
description: Automates custom git branch strategy action.
author: Jeongseok Kang

branding:
  icon: git-pull-request
  color: green

inputs:
  github-token:
    description: GitHub personal access token with privilege.
    required: true

runs:
  using: node20
  main: dist/index.js
