name: ghaflow
description: Automates custom git branch strategy action.
author: Jeongseok Kang

branding:
  icon: git-pull-request
  color: green

inputs:
  github-token:
    description: GitHub personal access token with privilege.
    required: true
  main-branch:
    description: Main branch.
    default: main
  release-branch: # 1.0[,2.0]
    description: Release branch(es). Allow comma-separated value to support multiple branches. (e.g. "1.0,2.0")
    required: false

runs:
  using: node20
  main: dist/index.js
