name: default

on:
  push:

permissions:
  contents: read
  pull-requests: write
  repository-projects: write  

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: rapsealk/ghaflow@c2cb17eee51ee840c5bb5d2eac030070ad38b2a5
