name: default

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  repository-projects: write  

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: rapsealk/ghaflow@a4f00d313ac9cbfb212a0c2c07a388a21ad0f9c6
